### PR TITLE
Setup and use local service-core to fix broken dependency

### LINKED ISSUE #36: Setup script not resolving components/api-server/package.json
Running ```make setup``` throws errors when trying to ```npm install```:

* At first, npm install failed because dev-site/package.json was referencing the production branch of service-core, which is not existing anymore :
>     "pryv-service-core": "git+ssh://git@github.com:pryv/service-core.git#production"
We patched this in dev-site/master by referencing service-core/release-1.1 instead.

* Now, npm install still fails with the following error:
```
Installing Node modules from 'package.json' if necessary...

npm ERR! code ENOLOCAL
npm ERR! Could not install from "node_modules/pryv-service-core/components/api-server" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/thiebaudmodoux/.npm/_logs/2017-11-27T15_58_02_648Z-debug.log
```

### PR DESCRIPTION
**Pull request by tmodoux**
Fix #36.

By cloning service-core in setup script and use local dependency in package.json (with file:).
Introduce a setup option (with default value) that allows to specify a branch for service-core.
Augment README with details about service-core dependency.

### CODE REVIEW

File: dev-env/setup.sh [hunk 1]
```diff
@@ -10,16 +10,37 @@ cd $scriptsFolder/..
...
+if [ ! -d dependencies/core ]
+then
+  echo "Setting up 'dependencies/core' folder for service-core dependency."
+  git clone git@github.com:pryv/service-core.git dependencies/core
+fi
+
+if [ -z "$1" ]
+then
+  # default branch used for service-core dependency
+  coreBranch="release-1.1"
```
Comment (kebetsi) [inline dev-env/setup.sh]: Same as Kaspar, we should use 1.2 as default

**Comment by kebetsi** [comment]
@tmodoux Can you add yarn as a prerequisite and fix the rest of the README accordingly, please?

**Comment by tmodoux** [comment]
Thanks for the reviews, merging it.
